"""rename git

Revision ID: f0d923ef1cd7
Revises: 1db4e9338b9b
Create Date: 2025-05-10 16:34:07.237434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d923ef1cd7'
down_revision: Union[str, None] = '1db4e9338b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profile_account', sa.Column('git', sa.Text(), nullable=True))
    op.drop_column('freelancer_profile_account', 'repositories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profile_account', sa.Column('repositories', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('freelancer_profile_account', 'git')
    # ### end Alembic commands ###
