"""added field created_at all tables

Revision ID: 59d0db697fa7
Revises: f0d923ef1cd7
Create Date: 2025-05-10 16:53:35.639259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d0db697fa7'
down_revision: Union[str, None] = 'f0d923ef1cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profile_account', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profile_account_language', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profile_account_stack', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_account_stack', 'created_at')
    op.drop_column('profile_account_language', 'created_at')
    op.drop_column('freelancer_profile_account', 'created_at')
    # ### end Alembic commands ###
