"""

Revision ID: 0e656364da00
Revises: 8b33ed2db061
Create Date: 2025-04-25 22:32:49.221812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e656364da00'
down_revision: Union[str, None] = '8b33ed2db061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_profiles', sa.Column('personal_url', sa.Text(), nullable=True))
    op.drop_column('freelancer_profiles', 'avg_response_time')
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at')
    op.add_column('freelancer_profiles', sa.Column('avg_response_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('freelancer_profiles', 'personal_url')
    # ### end Alembic commands ###
