"""added freelancer profile account model

Revision ID: 1db4e9338b9b
Revises: fc6537756b75
Create Date: 2025-05-10 16:21:11.977677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db4e9338b9b'
down_revision: Union[str, None] = 'fc6537756b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancer_profile_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('repositories', sa.Text(), nullable=True),
    sa.Column('personal_site_url', sa.Text(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('karma', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile_account_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['freelancer_profile_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_account_language_profile_id'), 'profile_account_language', ['profile_id'], unique=False)
    op.create_table('profile_account_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['freelancer_profile_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_account_stack_profile_id'), 'profile_account_stack', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_account_stack_profile_id'), table_name='profile_account_stack')
    op.drop_table('profile_account_stack')
    op.drop_index(op.f('ix_profile_account_language_profile_id'), table_name='profile_account_language')
    op.drop_table('profile_account_language')
    op.drop_table('freelancer_profile_account')
    # ### end Alembic commands ###
