DEV:
  postgresql:
    host: "localhost"
    port: null
    user: null
    password: null
    path: null
  redis:
    host: "localhost"
    port: null
  application:
    host: "localhost"
    domain: null
    port: 8080
    token: null
    administrators: [5892974145]
    chief_administrator: 5892974145
  nats:
    host: null
    port: null
    other_ports:
      monitoring: null


release:
  postgresql:
    host: "localhost"
    port: null
    user: null
    password: null
    path: null
  redis:
    host: "localhost"
    port: null
  application:
    host: "localhost"
    domain: null
    port: 8080
    token: null
    administrators: [ 5892974145 ]
    chief_administrator: 5892974145
  nats:
    host: null
    port: null
    other_ports:
      monitoring: null
